-- ====================================
-- SocialClubs Database Schema
-- Generated from Supabase via MCP
-- Project: pcfmjmdxaveiqrvrqauj
-- Date: 2025-12-13
-- ====================================

-- ====================================
-- CORE TABLES
-- ====================================

-- Users table (extends auth.users)
CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  username text UNIQUE NOT NULL,
  avatar_url text,
  bio text,
  is_member boolean,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE users IS 'Tabla con los datos principales de cada usuario';

-- Clubs table
CREATE TABLE clubs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text,
  logo jsonb,
  bio text,
  color text,
  level smallint CHECK (level <= 10),
  privacity text,
  creator uuid REFERENCES auth.users(id),
  tags json,
  total_members bigint,
  club_link text UNIQUE,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE clubs IS 'Esta tabla contiene los distintos clubes que existen y algunos valores sobre ellos';
COMMENT ON COLUMN clubs.club_link IS 'Unique random string for shareable club invite links (e.g., aB3xK9mQ)';

-- Users-Clubs relationship (membership)
CREATE TABLE users_clubs (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users(id),
  club_id uuid REFERENCES clubs(id),
  role text,
  points smallint,
  invite_code text,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE users_clubs IS 'Relacion entre usuarios y clubes';
COMMENT ON COLUMN users_clubs.points IS 'Club-specific gamification points for user';

-- ====================================
-- CONTENT & POSTS
-- ====================================

-- Posts table
CREATE TABLE posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id uuid REFERENCES clubs(id),
  content jsonb,
  type text,
  created_at timestamptz DEFAULT now()
);

-- Post statistics
CREATE TABLE post_stats (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  post_id uuid REFERENCES posts(id) DEFAULT gen_random_uuid(),
  likes bigint,
  superlikes bigint,
  comments bigint,
  user_views bigint
);
COMMENT ON TABLE post_stats IS 'Stats for each specific post';

-- Post interactions (likes, superlikes)
CREATE TABLE post_interactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES posts(id),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  interaction_type varchar CHECK (interaction_type IN ('like', 'superlike')),
  created_at timestamptz DEFAULT now()
);

-- Post comments
CREATE TABLE post_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid NOT NULL REFERENCES posts(id),
  user_id uuid NOT NULL REFERENCES auth.users(id),
  content text NOT NULL,
  parent_comment_id uuid REFERENCES post_comments(id),
  created_at timestamptz DEFAULT now()
);

-- Polls
CREATE TABLE polls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id uuid UNIQUE NOT NULL REFERENCES posts(id),
  question text NOT NULL,
  options jsonb NOT NULL CHECK (
    jsonb_typeof(options) = 'array' AND 
    jsonb_array_length(options) >= 2 AND 
    jsonb_array_length(options) <= 10
  ),
  is_anonymous boolean DEFAULT false,
  is_multiple_choice boolean DEFAULT false,
  allows_add_options boolean DEFAULT false,
  closes_at timestamptz,
  total_votes integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ====================================
-- MEMBERSHIPS & SUBSCRIPTIONS
-- ====================================

-- Memberships (subscription tiers)
CREATE TABLE memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id uuid REFERENCES clubs(id),
  price bigint,
  content jsonb
);
COMMENT ON TABLE memberships IS 'Lista de membresias creadas en la plataforma';

-- User memberships (active subscriptions)
CREATE TABLE users_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user uuid NOT NULL REFERENCES users(id),
  membership uuid NOT NULL REFERENCES memberships(id),
  status text NOT NULL,
  expire_date timestamp,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE users_memberships IS 'Lista de suscripciones activas y historicas';

-- ====================================
-- CHANNELS & MESSAGING
-- ====================================

-- Channels (chat channels within clubs)
CREATE TABLE channels (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club_id uuid REFERENCES clubs(id),
  name text,
  membership uuid REFERENCES memberships(id),
  type text -- 'escalonado' or 'extra'
);
COMMENT ON TABLE channels IS 'Todos los canales de los clubes';
COMMENT ON COLUMN channels.type IS 'para saber si es escalonado o extra';

-- Chat messages
CREATE TABLE chat_messages (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  channel_id bigint REFERENCES channels(id),
  user_id uuid REFERENCES users(id),
  content jsonb,
  type_message text,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE chat_messages IS 'Registro de todos los mensajes de chats';

-- ====================================
-- VIDEO CALLS & APPOINTMENTS
-- ====================================

-- Video call appointments (scheduling)
CREATE TABLE vcall_appointments (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club_id uuid REFERENCES clubs(id) ON DELETE CASCADE,
  creator_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  day_of_week smallint CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time NOT NULL,
  duration smallint DEFAULT 60 CHECK (duration > 0),
  price bigint CHECK (price >= 0),
  timezone text DEFAULT 'UTC',
  is_active boolean DEFAULT true,
  max_bookings_per_slot smallint DEFAULT 1,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
COMMENT ON TABLE vcall_appointments IS 'Agenda de Reservas creada por Clubs - Slots de disponibilidad del creador';
COMMENT ON COLUMN vcall_appointments.day_of_week IS '0=Sunday, 1=Monday, ..., 6=Saturday';
COMMENT ON COLUMN vcall_appointments.timezone IS 'Timezone IANA del creador (ej: America/New_York)';

-- User scheduled appointments (bookings)
CREATE TABLE users_agendas (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  club_id uuid REFERENCES clubs(id) ON DELETE CASCADE,
  appointment_id bigint REFERENCES vcall_appointments(id) ON DELETE CASCADE,
  date date NOT NULL,
  start_time time NOT NULL,
  end_time time NOT NULL,
  price bigint,
  payment_id uuid REFERENCES payments(id),
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  call_room_created boolean DEFAULT false,
  cancelled_at timestamptz,
  cancelled_by uuid REFERENCES auth.users(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
COMMENT ON TABLE users_agendas IS 'Consultas agendadas por usuarios - Bookings confirmados';
COMMENT ON COLUMN users_agendas.user_id IS 'Usuario que reservó la cita';
COMMENT ON COLUMN users_agendas.call_room_created IS 'Si ya se creó el room de Daily.co para esta cita';

-- Video call rooms (Daily.co rooms)
CREATE TABLE vcall_rooms (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club_id uuid REFERENCES clubs(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  creator_id uuid REFERENCES auth.users(id),
  booking_id bigint REFERENCES users_agendas(id) ON DELETE CASCADE,
  appointment_id bigint REFERENCES vcall_appointments(id),
  room_name text UNIQUE NOT NULL,
  link text NOT NULL,
  status text DEFAULT 'active' CHECK (status IN ('active', 'ended', 'expired')),
  expires_at timestamptz NOT NULL,
  ended_at timestamptz,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE vcall_rooms IS 'Video call rooms de Daily.co - Rooms activas o finalizadas';
COMMENT ON COLUMN vcall_rooms.room_name IS 'Nombre único del room en Daily.co';
COMMENT ON COLUMN vcall_rooms.user_id IS 'Usuario que reservó (miembro)';
COMMENT ON COLUMN vcall_rooms.creator_id IS 'Creador del club (quien da la consulta)';

-- ====================================
-- GAMIFICATION & ENGAGEMENT
-- ====================================

-- User points (superlikes, etc.)
CREATE TABLE usersPoints (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user uuid REFERENCES users(id),
  superlikes smallint DEFAULT 10
);
COMMENT ON TABLE usersPoints IS 'Tabla con puntajes de interacciones especiales de usuarios, en principio superlikes';

-- Club statistics
CREATE TABLE clubStats (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club uuid REFERENCES clubs(id),
  engagement smallint,
  revenue bigint,
  superlikes bigint,
  e integer,
  s integer,
  sd integer,
  gg integer,
  vvv integer,
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE clubStats IS 'Analiticas especificas de cada club';

-- Club badges
CREATE TABLE badge_club (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  club uuid REFERENCES clubs(id),
  founder boolean,
  title text,
  verification text
);
COMMENT ON TABLE badge_club IS 'Badges y otras simbologias especiales para clubs';

-- Referrals system
CREATE TABLE referrals (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  referral_id uuid REFERENCES users(id),
  referrer_id uuid REFERENCES users(id),
  club_id uuid REFERENCES clubs(id),
  created_at timestamptz DEFAULT now()
);
COMMENT ON TABLE referrals IS 'Table for the referrals system for clubs';

-- ====================================
-- GAMIFICATION SYSTEM
-- ====================================

-- Club Gamification Actions (Point Rules)
CREATE TABLE club_gamification_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id uuid REFERENCES clubs(id),
  type text NOT NULL,
  value integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE club_gamification_actions IS 'Defines point values for different actions within clubs';
COMMENT ON COLUMN club_gamification_actions.type IS 'Action type (e.g., post_created, comment_added, like_given)';
COMMENT ON COLUMN club_gamification_actions.value IS 'Points awarded for this action';

-- Club Gamification Rewards
CREATE TABLE club_gamification_rewards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id uuid REFERENCES clubs(id),
  responsibility text NOT NULL CHECK (responsibility IN ('promise', 'virtual')),
  bounty jsonb NOT NULL DEFAULT '{}'::jsonb,
  points_required integer NOT NULL CHECK (points_required >= 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'paused')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE club_gamification_rewards IS 'Rewards that users can claim with their club points';
COMMENT ON COLUMN club_gamification_rewards.responsibility IS 'Type of reward: promise (real-world) or virtual';
COMMENT ON COLUMN club_gamification_rewards.bounty IS 'Reward details (title, description, etc.)';
COMMENT ON COLUMN club_gamification_rewards.points_required IS 'Points needed to claim this reward';

-- ====================================
-- NOTIFICATIONS & FEEDBACK
-- ====================================

-- User notifications
CREATE TABLE notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id),
  type text,
  title text,
  body text,
  read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- User feedback messages
CREATE TABLE feedback_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES users(id),
  type text,
  content text,
  created_at timestamptz DEFAULT now()
);

-- ====================================
-- PAYMENTS & FINANCIALS
-- ====================================

-- Payments transactions
CREATE TABLE payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id),
  amount bigint CHECK (amount > 0),
  txn_type text CHECK (txn_type IN ('payment', 'payout', 'fee', 'refund')),
  txn_stripe_id text,
  status text CHECK (status IN ('pending', 'completed', 'failed')),
  direction text CHECK (direction IN ('in', 'out')),
  created_at timestamptz DEFAULT now()
);

-- Club balances
CREATE TABLE club_balances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id),
  total_earnings bigint DEFAULT 0,
  available_balance bigint DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);

-- Connected Stripe accounts
CREATE TABLE connected_stripe_accounts (
  id bigint PRIMARY KEY DEFAULT nextval('connected_stripe_accounts_id_seq'),
  user_id uuid REFERENCES users(id),
  stripe_account_id text UNIQUE,
  is_active boolean DEFAULT false
);

-- ====================================
-- ANALYTICS & METRICS
-- ====================================

-- Product metrics (platform-wide)
CREATE TABLE product_metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recorded_at timestamptz DEFAULT now(),
  connections_per_user numeric,
  mau integer, -- Monthly Active Users
  dau integer, -- Daily Active Users
  new_signups integer,
  avg_session_length_seconds integer,
  messages_per_user numeric,
  retention_rate_30d numeric,
  churn_rate numeric,
  revenue_cents bigint,
  notes text
);

-- ====================================
-- WIDGETS
-- ====================================

-- Widgets catalog
CREATE TABLE widgets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name varchar NOT NULL,
  schema jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Club widgets (instances)
CREATE TABLE club_widgets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id uuid NOT NULL REFERENCES clubs(id),
  widget_id uuid NOT NULL REFERENCES widgets(id),
  cache_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Club widgets data
CREATE TABLE club_widgets_data (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  club_widget_id uuid NOT NULL REFERENCES club_widgets(id),
  key varchar NOT NULL,
  value jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- ====================================
-- ROW LEVEL SECURITY (RLS)
-- ====================================

-- Enable RLS on tables
ALTER TABLE vcall_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_agendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE clubStats ENABLE ROW LEVEL SECURITY;
ALTER TABLE clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE usersPoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE users_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE badge_club ENABLE ROW LEVEL SECURITY;
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE vcall_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_stats ENABLE ROW LEVEL SECURITY;

-- ====================================
-- NOTES
-- ====================================

-- Total Tables: 33
-- Tables with RLS enabled: 15
-- Main features:
--   - Social clubs management
--   - Content posts with polls
--   - Membership tiers and subscriptions
--   - Video call appointments and rooms
--   - Chat channels and messaging
--   - Gamification system (points, rewards, actions)
--   - Badges and referrals
--   - Payments and financials (Stripe integration)
--   - AI agents for clubs
--   - Customizable widgets system
--   - Analytics and metrics tracking

-- ====================================
-- DATABASE FUNCTIONS (RPCs)
-- ====================================

-- Increment/Decrement Superlikes (Global Points)
CREATE OR REPLACE FUNCTION increment_superlikes(user_id_input uuid, amount_input integer)
RETURNS void AS $$
BEGIN
  UPDATE "usersPoints"
  SET superlikes = superlikes + amount_input
  WHERE "user" = user_id_input;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_superlikes(user_id_input uuid, amount_input integer)
RETURNS void AS $$
BEGIN
  UPDATE "usersPoints"
  SET superlikes = GREATEST(superlikes - amount_input, 0)
  WHERE "user" = user_id_input;
END;
$$ LANGUAGE plpgsql;

-- Post Stats Functions
CREATE OR REPLACE FUNCTION increment_like_count(post_id_input uuid)
RETURNS void AS $$
BEGIN
  UPDATE post_stats
  SET likes = likes + 1
  WHERE post_id = post_id_input;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_like_count(post_id_input uuid)
RETURNS void AS $$
BEGIN
  UPDATE post_stats
  SET likes = GREATEST(likes - 1, 0)
  WHERE post_id = post_id_input;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION increment_superlike_count(post_id_input uuid)
RETURNS void AS $$
BEGIN
  UPDATE post_stats
  SET superlikes = superlikes + 1
  WHERE post_id = post_id_input;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION decrement_superlike_count(post_id_input uuid)
RETURNS void AS $$
BEGIN
  UPDATE post_stats
  SET superlikes = GREATEST(superlikes - 1, 0)
  WHERE post_id = post_id_input;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION increment_comment_count(post_id_input uuid)
RETURNS void AS $$
BEGIN
  UPDATE post_stats
  SET comments = comments + 1
  WHERE post_id = post_id_input;
END;
$$ LANGUAGE plpgsql;

-- Gamification: Increment User Points in Club
CREATE OR REPLACE FUNCTION increment_user_points(
  p_user_id uuid,
  p_club_id uuid,
  p_points integer
)
RETURNS void AS $$
BEGIN
  UPDATE users_clubs
  SET points = COALESCE(points, 0) + p_points
  WHERE user_id = p_user_id AND club_id = p_club_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION increment_user_points IS 'Atomically increments user points in a club for gamification';

-- Search Clubs Function
CREATE OR REPLACE FUNCTION search_clubs_json(search_term text)
RETURNS jsonb AS $$
DECLARE
  result jsonb;
BEGIN
  SELECT jsonb_agg(club)
  INTO result
  FROM (
    SELECT 
      id, 
      name
    FROM 
      public.clubs
    WHERE 
      name ILIKE '%' || search_term || '%'
    LIMIT 50
  ) AS club;

  RETURN result;
END;
$$ LANGUAGE plpgsql;

-- ====================================
-- TRIGGERS
-- ====================================

-- Trigger: Handle New User (auth.users -> public.users)
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.users (
    id, 
    name, 
    username, 
    avatar_url, 
    created_at
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'name', ''),
    COALESCE(new.raw_user_meta_data->>'username', ''),
    NULL,
    NOW()
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- Trigger: Update club_reports.updated_at
CREATE OR REPLACE FUNCTION update_club_reports_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_club_reports_timestamp
  BEFORE UPDATE ON club_reports
  FOR EACH ROW EXECUTE FUNCTION update_club_reports_updated_at();
